### PR TITLE
New main page describing our project

### PR DESCRIPTION
**Pull request by jalohse**

### CODE REVIEW

**Comment by doctor-g** [comment]
The site needs some additional development before it is merged into main. However, there seems to be a defect somewhere in the build system, since what this branch is building _is_ being pushed live to github.io. (Probably a problem with how I am handling the branch-specific logic.)

Specific improvements to make:
* Current HTML structure is an _ad hoc_ mix of stylesheets and inline styles, which is the worst of both worlds. I recommend putting all the layout into the stylesheet.
* Play button very small and easy to miss, but should be prominent
* Insufficient use of game assets, like our game logo and team logo, for branding purposes

I think @zbruh has some skills in this area, so maybe he can jump on too.

**Comment by zbruh** [comment]
I can start working on the stylesheet if @jalohse hasn't already.

I also have another suggestion--currently, if someone goes to spring-studio-2016.github.io, they get a 404. I'm not sure how hard this would be, but I know that if we move this over to a repository called `spring-studio-2016.github.io`, it could serve the main page for our team. Then, the `monsters` repository could focus more on the game itself.

Obviously, we don't have to do this, but I thought I would suggest it. Let me know if you guys think this is a good idea--I'd be glad to help out with doing this as well.

**Comment by doctor-g** [comment]
The existing branch has a stylesheet but also some inline styles. Unifying these would be beneficial for maintenance and clarity.

I was not aware of "user & organization pages"---thanks for the link. I like the idea of putting the info page at the simpler URL. We could even change the organization name to "studio-368" probably, though that's something we should do together to stress-test connectivity via keys, scripts, etc. So, if we want to rename the organization, then it seems the steps would be to do that, then create a `studio-368.github.io` repository, whose master would be pushed to that URL (if I understand it correctly). You could just try it with the current name too, to see if all the pieces work together as expected.

Let me know if you need me to do anything to move forward.

**Comment by doctor-g** [comment]
Since we're going to take @zbruh's suggestion of putting in an organization page instead of managing a suite of web pages in the project repository, I'm going to close this PR.

**Pull request closed without merging**
